[package]
name = "yclass_config"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ItsEthra/yclass"
authors = ["ItsEthra"]

[dependencies]
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
